### Ver calificaciones por curso y periodo
GET http://localhost:3000/calificaciones/curso    
Content-Type: application/json

{
    "curso": "Calculo I",
    "cuenta_id": "20212000020"
}

### Ver docentes y los cursos que imparten
GET http://localhost:3000/calificaciones/docente/cursos/20212000020


### Ver estudiantes que están inscritos en un curso por docente
GET http://localhost:3000/calificaciones/docente/estudiantes
Content-Type: application/json

{
    "cuenta_id": "20212000020",
    "curso": "Calculo I",
    "periodo": 1
}

### Inscribir un docente a un curso
POST http://localhost:3000/calificaciones/docente/inscripcion
Content-Type: application/json

{
    "cuenta_id": "20212000020",
    "curso": "Biología Celular",
    "periodo": 1
}


### Ingresar calificaciones de un estudiante a un curso según el docente
POST http://localhost:3000/calificaciones
Content-Type: application/json

{
    "curso": "Arte Moderno",
    "cuenta_id": "20212000005",
    "nota": 99.9,
    "periodo_id": 1 ,
    "subperiodo_id": 2 
}

### Actualizar calificaciones de un estudiante a un curso según el docente
PATCH http://localhost:3000/calificaciones
Content-Type: application/json

{
    "curso": "Arte Moderno",
    "cuenta_id": "20212000005",
    "nota": 98.9,
    "periodo_id": 1 ,
    "subperiodo_id": 2 
}

